version: '3.8'

services:

  backend:
    build: ./services/backend
    ports:
      - "${DB_PORTS}:${DB_PORTS}"
    environment:
      - DATABASE_URL="${DATABASE_URL}"
      - SECRET_KEY="${SECRET_KEY}"
    volumes:
      - ./services/backend:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000
    depends_on:
      - db

  frontend:
    build: ./services/frontend
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    ports:
      - "${APP_PORTS}:${APP_PORTS}"

  db:
    image: ${DB_IMAGE}
    expose:
      - ${DB_PORTS}
    environment:
      - POSTGRES_USER: ${DB_USER}
      - POSTGRES_DB: ${DB_NAME}
      - POSTGRES_PASS: ${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
